name: 🧪 Unittests with Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run Tests with Coverage
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Run tests & coverage
        run: uv tool run nox -s test_source

      - name: Store coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          include-hidden-files: true
          path: coverage_report/

  upload-coverage:
    name: Upload coverage to Coveralls
    needs: [run-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-data
          path: coverage_report/

      - name: Coveralls Upload
        uses: coverallsapp/github-action@v2
        with:
          fail-on-error: false
          file: coverage_report/cov.xml
